### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by linuxoid69** [peter-evans/repository-dispatch#10]
Hello. I have the error in my project "##[error]Bad credentials"
https://github.com/linuxoid69/go-backuper/runs/533775840?check_suite_focus=true
I created a token with maximum permissions.
REPO_ACCESS_TOKEN
screenshot -> https://imgur.com/a/3tGZeIw
What am I doing wrong?

**Comment by peter-evans** [comment]
Hi @linuxoid69 

Your screenshot shows that you created a token called `REPO_ACCESS_TOKEN`. Did you also copy the token string and create a secret called `REPO_ACCESS_TOKEN` in the repository containing your workflow? It should be created at https://github.com/linuxoid69/go-backuper/settings/secrets

**Comment by linuxoid69** [comment]
> Hi @linuxoid69
> 
> Your screenshot shows that you created a token called `REPO_ACCESS_TOKEN`. Did you also copy the token string and create a secret called `REPO_ACCESS_TOKEN` in the repository containing your workflow? It should be created at https://github.com/linuxoid69/go-backuper/settings/secrets

Success ))). Thank you very much for your help.
