### ISSUE TITLE
404 Error on hitting github dispatches API 

### ISSUE THREAD

**Issue by kalebsembiring** [peter-evans/repository-dispatch#103]
occasionally can't hit the github dispatches API, here's the error logs :

**Run peter-evans/repository-dispatch@689b4c9c3d042832e6256022025ff57a898fcb82
  with:
    token: ***
    repository: tokopedia/ansible-v2
    event-type: apply
    client-payload: { "pr_number": "20897", "extra_vars": "", "tags": "", "limit": "", "comment_body": "ghtoped apply", "pr_url": "https://api.github.com/repos/tokopedia/ansible-v2/pulls/20897"}
  env:
    GCS_FILE: true
    COMMENT_BODY: ghtoped apply
Error: request to https://api.github.com/repos/tokopedia/ansible-v2/dispatches failed, reason: getaddrinfo ENOTFOUND api.github.com**

**Comment by peter-evans** [comment]
Hi @kalebsembiring 

If it's just happening occasionally then it's likely to be a network problem between the runner and the API, or it could be intermittent API problems on GitHub's side.

Are you using self-hosted runners, or GitHub hosted runners?

**Comment by kalebsembiring** [comment]
Hi @peter-evans, thank you for your fast feedback!

Currently, we're using self-hosted runners at GCP for running our action and each runner has a separate VPC network. 
Is there any chance we can retry the action whenever the Github API is unreachable or timeout?

Thank you in advance!

**Comment by peter-evans** [comment]
Hi @kalebsembiring 

It's generally not good practice to retry 4XX errors, so I would like to avoid that in the action.

I think the best thing to do would be to fix your networking issues. It is certainly not normal to occasionally lose connectivity like that. Alternatively, you can retry the action in the workflow itself.
