### ISSUE TITLE
If repository dispatch is not found

### ISSUE THREAD

**Issue by ag-monk** [peter-evans/repository-dispatch#104]
I have a main workflow which triggers multiple repos having repository dispatch. Is it possible to put a condition to check if repository dispatch is not present in any of the downstream repos then that repository execution can be skipped by main workflow? If not, then how to handle conditional scenarios with repository dispatch?

**Comment by peter-evans** [comment]
Hi @ag-monk 

If there is no `repository_dispatch` workflow in the target repository then the event doesn't trigger anything. There is no harm in sending the event, even if the target workflow doesn't have a workflow.

There is no convenient way to check. If you really need to check, for some reason, then you could do this yourself in the workflow by checking out the target repository and making sure a workflow file exists.
