### ISSUE TITLE
Please update the following actions to use Node.js 16

### ISSUE THREAD

**Issue by binge8** [peter-evans/repository-dispatch#119]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: peter-evans/repository-dispatch

**Comment by peter-evans** [comment]
Hi @binge8 

This action already supports Node 16. Please update to the latest version.
