### ISSUE TITLE
Bump minimatch version

### ISSUE THREAD

**Issue by chaor** [peter-evans/repository-dispatch#129]
Hi Peter,

I want to use this github action in my work, but the security team says minimatch@3.0.4 has a high vulnerability. Is it possible to bump this package's version? Thanks!

**Comment by peter-evans** [comment]
Hi @chaor 

I realised that I had configured dependabot to ignore some updates unintentionally. I've patched this now and released a new version of the action. (`v2.1.1` / `v2`)

Thank you!

**Comment by chaor** [comment]
Thank you for the quick response! I see main branch still has minimatch@3.0.4 (https://github.com/peter-evans/repository-dispatch/blob/main/package-lock.json#L740). Is it possible to upgrade this package version?
Per https://www.npmjs.com/package/minimatch?activeTab=versions, 3.0.4 was released 6 years ago.

**Comment by peter-evans** [comment]
What you have linked to there just means that the package `@eslint/eslintrc` requires _at least_ version `3.0.4`, but the actual version of `minimatch` is now updated to `3.1.2`, as you can see [here](https://github.com/peter-evans/repository-dispatch/blob/main/package-lock.json#L12152-L12160).

GitHub's security alert in this repository is gone now. So it's updated fine.

**Comment by chaor** [comment]
Great, thank you Peter!
