### ISSUE TITLE
Can't seem to use `public_repo`

### ISSUE THREAD

**Issue by naugtur** [peter-evans/repository-dispatch#136]
The documentation says 

> you can use the more limited public_repo scope.

which doesn't seem to be true (from both reading GH docs and trying it out)

Did you get it to work that way? Maybe it depends on a setting.

**Comment by peter-evans** [comment]
Hi @naugtur 

I tested it just now and it still works. Remember that the user account that you create the token on still needs to have `write` access to the repository, it's just that the token itself has limited scope.

My test:
- Added workflow using `public_repo` scope token: https://github.com/peter-evans/repository-dispatch/commit/08947cd28e886d5ea6d89bead081aefce9ec6736
- Executed run: https://github.com/peter-evans/repository-dispatch/actions/runs/3745231909
- Triggers `repository_dispatch` event: https://github.com/peter-evans/repository-dispatch/actions/runs/3745232704
