### ISSUE TITLE
The action should be able to set the inputs for the workflow that's being dispatched

### ISSUE THREAD

**Issue by kanhayaKy** [peter-evans/repository-dispatch#146]
If a workflow that needs to be dispatched requires some input parameters there is option to set these input parameters from this action.

**Comment by peter-evans** [comment]
Hi @kanhayaKy 

I think what you are looking for is [workflow-dispatch](https://github.com/benc-uk/workflow-dispatch). `repository_dispatch` doesn't have input parameters.
