### ISSUE TITLE
fine-grained personal access tokens

### ISSUE THREAD

**Issue by verhovsky** [peter-evans/repository-dispatch#165]
PATs seem to be more complicated now, I couldn't just choose "public_repo" permissions, I had to choose whether to not allow, allow read-only or allow read/write for like 30 different things.

https://github.com/settings/personal-access-tokens/new

I chose 6 that looked good, and it seems to have worked but I forget which ones I chose and I don't think I can see. It would be great if the documentation listed the permissions that need to be set.

**Comment by peter-evans** [comment]
Hi @verhovsky 

I haven't tested fine-grained PATs with this action yet, but I think the only scope you need is `contents: write`.

This is mentioned in the readme [here](https://github.com/peter-evans/repository-dispatch#action-inputs).

**Comment by caendesilva** [comment]
From my granular testing, fine grained tokens (for organizations at least) only require "Read and Write access to code", so `contents: write`, but, and this is important, the token MUST belong to the person who owns (created) the repository. See https://github.com/orgs/community/discussions/36441#discussioncomment-5303205

**Related research:**

Based on the docs it seems like you should only need `actions: write` permissions
> https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#actions

(There is also a general `repository_dispatch` endpoint which uses `contents: write` but that I think is unrelated
> https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_dispatch

There is also some somewhat conflicting documentation that I think is not updated to include fine grained tokens, which states that access tokens need the `repo` scope, and Apps need the `actions:write`
> https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
