### ISSUE TITLE
payload output

### ISSUE THREAD

**Issue by omarkorety** [peter-evans/repository-dispatch#250]
my paylaod is like this
`  client-payload: '{"image": "omar/test:${{ steps.previoustag.outputs.tag }}", "min_req": {"search-dev": "1.0.0","rasa-en-dev": "5.0.0","rasa-ar-dev": "1.0.0","action-dev": "1.0.0"}}'
`
 when i trying to use min_req iby using echo 
`        echo    "${{ github.event.client_payload.min_req }}"
`
the expected output is the value of min_req
`{"search-dev": "1.0.0","rasa-en-dev": "5.0.0","rasa-ar-dev": "1.0.0","action-dev": "1.0.0"}`

but it appears as 
`echo "Object" `
and i cant access it even when using jq to get all payload object by using this 
```
    - run: |
        export min_req_value=$(echo "${{ github.event.client_payload }}" | jq -r '.min_req')
        echo "$min_req_value"
```

**Comment by peter-evans** [comment]
@omarkorety Sorry, I don't know how to fix this. It might be best to ask for help on Stackoverflow where some jq experts can help you.
