### ISSUE TITLE
Question: Github Token

### ISSUE THREAD

**Issue by oba11** [peter-evans/repository-dispatch#3]
> This is a question

Thanks for the GitHub Action, I want to ask if I can use `${{ secrets.GITHUB_TOKEN }}` with this action?

Thanks.

**Comment by peter-evans** [comment]
Hi @oba11 

Unfortunately not. `GITHUB_TOKEN` is only scoped to the current repository so it is necessary to use a `repo` scoped [Personal Access Token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).

This is also mentioned in the [documentation for the API](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event)

> To give you write access to the repository, you must use a personal access token with the repo scope.

**Comment by oba11** [comment]
Thank you so much @peter-evans

**Comment by peter-evans** [comment]
@metaclips, there is no difference for orgs, a personal access tokens with `repo` scope is still required. The default `GITHUB_TOKEN` in repositories will not work. See [this section](https://github.com/peter-evans/repository-dispatch#token) of the readme.

**Comment by NikhilaMeka** [comment]
@peter-evans I'm triggering repository_dispatch from repo 1 to repo 2, I have given repository_dispatch_token personalized token at org level while triggering the event. My trigger is failing with "Error: Repository not found, OR token has insufficient permissions." Do you have any thoughts on what I'm missing here?

**Comment by peter-evans** [comment]
@NikhilaMeka It's exactly as the message describes. Either there is a mistake in the repository name and the action couldn't find it, or the provided token doesn't have the correct permissions. The token must have the `repo` scope and be created on a user that has `write` access to the repository. See the documentation [here](https://github.com/peter-evans/repository-dispatch#token).

**Comment by Jaykob** [comment]
You can use this one here to get a repo scoped token through a GitHub App:
[https://github.com/tibdex/github-app-token](https://github.com/tibdex/github-app-token)
