### ISSUE TITLE
##[error]Not Found on every run

### ISSUE THREAD

**Issue by dor-cyolo** [peter-evans/repository-dispatch#34]
Error I get. What am I missing? Really want this to work.

with:
    token: ***
    event-type: my-event
    client-payload: {"ref": "refs/heads/master", "sha": "f71d129c3362c56acf734863f873aa8bb3281459"}
    repository: ******
##[error]Not Found

name: Alert parent repository on push
on:
  push:
    branches:
      -  **********

jobs:
  dispatch:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          #repository: test-dispatch
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

Another job waitingto this event does exist and everything.

**Comment by peter-evans** [comment]
Hi @dor-cyolo 

The error looks like it can't find the repository that you want to create the dispatch for. Are you trying to send a `repository_dispatch` event to a different repository than the one the workflow is running in? If so, you need to specify the `repository` input. The format of the `repository` input is `<owner>/<repository>`. For example, `dor-cyolo/other-repo`.

**Comment by dor-cyolo** [comment]
I actually tried both with <owner>/<other-repo> and  <organization>/<other-repo> and it results the same. 
Maybe something with github? Do I need a special kind of subscription in order to make this work?

**Comment by peter-evans** [comment]
Any GitHub user account will work. You just need a `repo` scoped PAT associated with a user that has `write` access to the repository. 

Please show me your workflow. What you pasted in the original issue shows that you commented out the `repository` input. I need to see exactly what you are trying.

**Comment by peter-evans** [comment]
I'm going to close this issue for now because I'm fairly sure this is not a problem with the action itself. Feel free to continue the conversation if you need further help.

**Comment by GaushiDevOps** [comment]
hi...my trigger to CD job using your API is getting passed but it ain't triggering the the other workflow.
I wanted to trigger the CD workflow from a specific branch which is in another repository.
