### ISSUE TITLE
Custom branch support for "repository_dispatch"

### ISSUE THREAD

**Issue by sunn-e** [peter-evans/repository-dispatch#39]
Hi,
I'm trying to trigger a github actions workflow in a non-default branch. Is there any way I can do that using your Action?
I want to run workflow on custom branch.

I tried dispatch using just appending "/custom_branch_name",
like "sunn-e/myRepo/dev" , it showed green tick but did not actually trigger, s in it was not received.

**Comment by peter-evans** [comment]
Hi @sunn-e 

It's not possible with `repository_dispatch`. I would recommend trying [`workflow_dispatch`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) instead. That event does allow you to target a non-default branch.

If you are looking for an action to help you trigger the event, [this one](https://github.com/benc-uk/workflow-dispatch) looks like it will do the job. I've not tested it personally.

**Comment by sunn-e** [comment]
Thank you.
