### ISSUE TITLE
Checking on endpoint's response to set success or failed status

### ISSUE THREAD

**Issue by oleng** [peter-evans/repository-dispatch#49]
First I apologized if this isn't the right place to ask since I don't know where to find official Github API's channel or repo to ask.     
I went through the developer and newer API docs as well as your source code, I'd think there'd be a response either `204` or `4xx` code that can be returned to the action's to determine if the `POST` request actually delivered & acknowledged, but I didn't find it when I read the job run log. It seems like a missed opportunity to be able to flag the step as successful with better confidence.

Can it be implemented?

**Comment by peter-evans** [comment]
Hi @oleng 

If the API request to create a dispatch is successful it returns `204` and this action will exit as `success`. If the request fails (`4xx`, `5xx`) then the action will exit as `failed` with an error message.

This action can only return whether or not the dispatch was successfully created. Unfortunately, it cannot know if the dispatch successfully triggered a workflow or not. Is that what you mean?

**Comment by peter-evans** [comment]
If the action succeeds, you can assume with high degree of confidence that the API request was made successfully. If the action fails, for any reason, the API request was not made successfully. By default, if a workflow fails GitHub creates a notification that the workflow failed. So without complicating the solution any further, you already have a notification when the API request fails to be made. What is missing for you that this default doesn't cover?

**Comment by peter-evans** [comment]
Closing this for now.

I'm not opposed to adding features to the action if it makes sense and there is a clear use case for it. Feel free to continue the conversation.
