### ISSUE TITLE
How can I trigger a repository dispatch event on non-master branch?

### ISSUE THREAD

**Issue by shridharkalagi** [peter-evans/repository-dispatch#5]

**Comment by peter-evans** [comment]
Hi @shridharkalagi 

As far as I'm aware, this is not possible. The [dispatches API](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) does not support specifying a target branch. So all `repository_dispatch` events will target the master branch.

If this changes in future I will update the action to support it.

**Comment by shridharkalagi** [comment]
Thank you @peter-evans

**Comment by ryanprater** [comment]
Hey @peter-evans, great action, super useful!
Could you please update the readme to indicate this?
I had to go through some frustration before searching the issues and finding this :)

**Comment by peter-evans** [comment]
@ryanprater Updated the example with a note about this. Thanks!

**Comment by oleng** [comment]
Hi @peter-evans, a quick question, if the event dispatch configured from a non-master branch workflow to another github repo's master branch, does it work? I tried it on a hugo static build (in a `hugo` branch) and even though it passed without failure there's no log on `POST` sent and the action .yml didn't start in the target repo, so I'm confused.
