### ISSUE TITLE
Workflows not triggering

### ISSUE THREAD

**Issue by petja-laitila** [peter-evans/repository-dispatch#53]
Hello,
I have bunch of workflows that i'd like to manage with this action.
Problem is workflows that are supposed to get triggered are not triggerin.
I have followed instructions at https://stevenmortimer.com/running-github-actions-sequentially/ .
At the moment my workflows are defined only in one branch. Is that a problem for this action?

I'm doing something like this as per instructions as a last part of my first workflow:

      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-test-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

And this is the next workflow start:

    name: Next test workflow
    on:
      repository_dispatch:
        types: [trigger-test-worflow]

Edit. Just read that it only triggers if it's in main branch. I guess this just turned into feature request if it's possible to implement.

**Comment by peter-evans** [comment]
Hi @petja-laitila 

> Edit. Just read that it only triggers if it's in main branch. I guess this just turned into feature request if it's possible to implement.

Yes, it will only trigger for workflows on the repository's default branch.

I'm afraid there is nothing I can do to support triggering workflows on non-default branches. That is the way [`repository_dispatch`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch) events work on GitHub. Perhaps [`workflow_dispatch`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch) events would suit your use case. They can be targeted to non-default branches. [This action](https://github.com/marketplace/actions/workflow-dispatch) might help you with trying that approach.

**Comment by petja-laitila** [comment]
Thank for your response! I'll look into action you linked.
