### ISSUE TITLE
Support WorkflowID when Triggering another Repository

### ISSUE THREAD

**Issue by Paebbels** [peter-evans/repository-dispatch#55]
I found your workflow to trigger another (or same in my case) repository. The essential part about this idea, which is way easier implemented in GitLab) is to trigger upstream pipelines. This needs a way to trigger another workflow.

By looking at https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event, a `workflow_id` is supported in REST API. Can you please add a `workflow` parameter to your action?

![image](https://user-images.githubusercontent.com/956109/103167449-82316180-482b-11eb-9295-db78aec36538.png)

**Comment by peter-evans** [comment]
Hi @Paebbels 

What you have linked is a different API to the one used by this action. There are two similar APIs, [`repository_dispatch`](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event) (supported by this action) and [`workflow_dispatch`](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event).

If you are looking for an action to help you create a `workflow_dispatch` event, [this one](https://github.com/benc-uk/workflow-dispatch) looks like it will do the job. I've not tested it personally.
