### ISSUE TITLE
Repository-dispatch to list of repositories

### ISSUE THREAD

**Issue by FDenker** [peter-evans/repository-dispatch#75]
Hi,
I love using your action script. However, I was wondering whether it is possible to repository-dispatch a whole of repos as targets?

Thanks again for developing this awesome tool!

**Comment by peter-evans** [comment]
Hi @FDenker 

Glad you find the action useful.

Please see this example for how to dispatch to a list of repositories.
https://github.com/peter-evans/repository-dispatch#dispatch-to-multiple-repositories
