### ISSUE TITLE
check the status of "Repository Dispatch" workflow?

### ISSUE THREAD

**Issue by jaya-venkatesan** [peter-evans/repository-dispatch#81]
How to check in my next step to "Repository Dispatch"  workflow status ?
   

  - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: *****
          repository: username/anotherrepo 
          event-type: my-event
          client-payload: '{"sample": "${{ env.sample}}"}'

 - name: ....

**Comment by peter-evans** [comment]
Hi @jaya-venkatesan 

Unfortunately there is no easy way to do that. Please see my comment here on a similar issue. https://github.com/peter-evans/repository-dispatch/issues/78#issuecomment-864336799
