### ISSUE TITLE
Include a link to the dispatched workflow

### ISSUE THREAD

**Issue by FalconerTC** [peter-evans/repository-dispatch#83]
It would be awesome if after dispatching a workflow, this action could log the URL to the active workflow of the receiver. Maybe this just required querying Github for the run number once the run has been scheduled?

**Comment by peter-evans** [comment]
Hi @FalconerTC 

I would love to be able to do this, but unfortunately I don't think it's possible. GitHub's API doesn't return a response indicating any workflow(s) that the `repository_dispatch` event triggered. It's sort of fire-and-forget behaviour. I don't expect this behaviour to change any time soon, either.

If you want to display the URL somewhere, for example a PR comment, my suggestion would be the following:
1. When you make the dispatch, include details of where you would like to have the URL posted. For example, for a PR comment you would need to send the repository name and issue number.
1. In the triggered workflow, build a URL to the run using the `$GITHUB_RUN_ID`.
1. Using the repository name and issue number sent in the `client_payload` create a comment with the URL.

The last example on this page demonstrates this idea.
https://github.com/peter-evans/slash-command-dispatch#responding-to-the-comment-on-command-completion

**Comment by peter-evans** [comment]
> Maybe this just required querying Github for the run number once the run has been scheduled?

I forgot to address this idea. The main problem with querying GitHub's API for the scheduled run is that I don't think it's possible to know for sure which run was triggered by the run making the dispatch. i.e. If two dispatches are made at roughly the same time, I don't think it's possible to know which is which.

**Comment by peter-evans** [comment]
Closing this for now, but feel free to continue the conversation.
