### ISSUE TITLE
When I try start trigger I get error Error: Parameter token or opts.auth is required. but this field did fill

### ISSUE THREAD

**Issue by alexander-kondratyev** [peter-evans/repository-dispatch#92]
My YML
![Screenshot_2](https://user-images.githubusercontent.com/47692437/146444172-7e9366a9-d056-4303-9f00-0a2b4bd95ccc.jpg)

But I get error
![Screenshot_1](https://user-images.githubusercontent.com/47692437/146444360-2c4feeb4-d90e-4002-9704-d27c439773cc.jpg)

Peter, check this please

**Comment by peter-evans** [comment]
Hi @AlexanderKondrat 

It's difficult to know without seeing the actual workflow, but I think your YAML is probably malformed. Check the whitespace around your inputs.

**Comment by alexander-kondratyev** [comment]
@peter-evans Perhabs, I found a problem. I did use **token: ${{ secrets.my_token }}** and when I replace on **token: my_token**, the job have run. But when on another repository all jobs completed, "the repository-trigger" never not get feedback.

May be exist another way get feedback from repository-listener after complete job?
![Screenshot_1](https://user-images.githubusercontent.com/47692437/146817327-7cdd8202-eb24-4214-8c9c-d13c6210a5af.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/47692437/146817373-8902c4dc-6ba9-4828-a9d3-b8e940e557e8.jpg)

**Comment by peter-evans** [comment]
There is no easy way to get feedback. It's kind of "fire and forget" behaviour.
See my comment here: https://github.com/peter-evans/repository-dispatch/issues/78#issuecomment-864336799
