### ISSUE TITLE
Can I fail the source job if the target job failed?

### ISSUE THREAD

**Issue by roimor** [peter-evans/repository-dispatch#93]
need something like 'wait on check' but a more dynamic one... i think i saw some solution for it in one of your repos but cant find it now

**Comment by peter-evans** [comment]
Hi @roimor 

There's no easy solution to this, unfortunately. You would need to post the result to some shared resource that both the source job and target job know. Perhaps you saw the idea in this issue? https://github.com/peter-evans/repository-dispatch/issues/78
